# Generated by Django 4.2.20 on 2025-04-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0012_interest_image'),
        ('compatibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мин. возраст')),
                ('age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. возраст')),
                ('alcohol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.alcohol', verbose_name='Алкоголь')),
                ('children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.children', verbose_name='Дети')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.city', verbose_name='Город')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.education', verbose_name='Образование')),
                ('interests', models.ManyToManyField(blank=True, to='authuser.interest', verbose_name='Интересы')),
                ('languages', models.ManyToManyField(blank=True, to='authuser.language', verbose_name='Языки')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.religion', verbose_name='Религия')),
                ('smoking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.smoking', verbose_name='Курение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_settings', to='authuser.user')),
                ('zodiac_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.zodiac', verbose_name='Знак зодиака')),
            ],
            options={
                'verbose_name': 'Настройки поиска',
                'verbose_name_plural': 'Настройки поиска',
            },
        ),
    ]
