# Generated by Django 4.2.20 on 2025-04-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0012_interest_image'),
        ('compatibility', '0002_comparisonsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairsCritetia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Значительно важнее'), (2, 'Немного важнее'), (3, 'Одинаково'), (4, 'Немного менее важно'), (5, 'Значительно менее важно')], default=3)),
                ('criterion_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_a', to='compatibility.criterion')),
                ('criterion_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_b', to='compatibility.criterion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.user')),
            ],
            options={
                'ordering': ['criterion_a', 'criterion_b'],
                'unique_together': {('user', 'criterion_a', 'criterion_b')},
            },
        ),
    ]
