# Generated by Django 4.2.20 on 2025-04-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0012_interest_image'),
        ('compatibility', '0003_pairscritetia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PairsCritetia',
            new_name='PairsCriteria',
        ),
        migrations.CreateModel(
            name='CriterionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('consistency_ratio', models.FloatField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compatibility.criterion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.user')),
            ],
            options={
                'unique_together': {('user', 'criterion')},
            },
        ),
    ]
