# Generated by Django 4.2.20 on 2025-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionweight',
            name='consistency_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
