# Generated by Django 4.2.20 on 2025-03-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alcohol_children_city_education_language_religion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='emodji_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='authuser.language'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='smoking',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.gender'),
        ),
    ]
