# Generated by Django 4.2.20 on 2025-03-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_rename_theme_id_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
