# Generated by Django 4.2.20 on 2025-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_theme_alter_profile_theme_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='theme_id',
            new_name='theme',
        ),
    ]
