# Generated by Django 4.2.20 on 2025-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
