# Generated by Django 4.2.20 on 2025-03-25 21:20

import authuser.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0010_remove_profile_music_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo5',
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=authuser.models.profile_photo_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='authuser.profile')),
            ],
        ),
    ]
