# Generated by Django 4.2.20 on 2025-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0014_profile_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='uuid',
            field=models.CharField(default=1, max_length=22),
        ),
    ]
