# Generated by Django 4.2.20 on 2025-04-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0015_profilephoto_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emodji_id',
        ),
    ]
